### ISSUE TITLE
Fix bugs

### ISSUE THREAD

**Issue by xiqi-zheng** [Jordan-Teaching-Technologist/Team-B#26]
✔ 1. Smell need to disappear after Cheese's death   @xiqi-zheng 
2. Cheese cannot climb over all the walls    @Lzm03 
3. There will be flickering and stuttering when players enter their names on the room page  @ZehuaLiuY 
4. When refreshing the room, it may get stuck     @ZehuaLiuY 
5. Countdown time did not pause after the game ended    @xiqi-zheng 
6. Cannot exit after the game ends

**Comment by ZehuaLiuY** [comment]
3 & 4 fiexd :p https://github.com/Jordan-Teaching-Technologist/Team-B/tree/inroom-related-things

**Comment by ZehuaLiuY** [comment]
Fixed all bugs above
